
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/STARTER-team01
owner: ucsb-cs156-s25
repo_name: STARTER-team01
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-add-async-jobs","number":8,"title":"pc - add sync job capability","url":"https://github.com/ucsb-cs156-s25/STARTER-team01/pull/8"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-bump-spring-boot-version","number":6,"title":"pc - bump spring boot starter version to latest","url":"https://github.com/ucsb-cs156-s25/STARTER-team01/pull/6"}]
